[[plugins]]
repo = 'Shougo/deol.nvim'
lua_add = "require('plugins.deol')"

[[plugins]]
repo = 'vim-denops/denops-shared-server.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'mechatroner/rainbow_csv'

[[plugins]]
repo = 'LeafCage/vimhelpgenerator'

[[plugins]]
repo = 'k16em/dict-downloader'
hook_add = '''
  let g:dict_downloader_save_path = "~/.skk"
  let g:dict_downloader_dicts = [
    \   "https://skk-dev.github.io/dict/SKK-JISYO.L.gz",
    \   "https://raw.githubusercontent.com/k16em/skkdicts/refs/heads/main/SKK-JISYO.mtg",
    \   "https://raw.githubusercontent.com/k16em/skkdicts/refs/heads/main/SKK-JISYO.kei-s16"
    \ ]
'''

